# Generated by Django 3.2.6 on 2021-08-24 19:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftstarttime', models.TimeField()),
                ('shiftendtime', models.TimeField()),
            ],
            options={
                'unique_together': {('shiftstarttime', 'shiftendtime')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift1employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shift_1', to=settings.AUTH_USER_MODEL)),
                ('shift2employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shift_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('shift', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ManyToManyField(to='account.Shift')),
            ],
            options={
                'unique_together': {('date', 'employee')},
            },
        ),
    ]
