# Generated by Django 3.2.6 on 2021-08-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rankpreference_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankpreference',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='rankpreference',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shift1employee',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shift2employee',
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='RankPreference',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
