# Generated by Django 3.2.6 on 2021-08-24 21:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20210825_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftstarttime', models.TimeField()),
                ('shiftendtime', models.TimeField()),
            ],
            options={
                'unique_together': {('shiftstarttime', 'shiftendtime')},
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rank', models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.shift')),
            ],
            options={
                'unique_together': {('employee', 'date', 'shift')},
            },
        ),
    ]
