# Generated by Django 3.2.6 on 2021-08-24 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210825_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
