# Generated by Django 3.2.6 on 2021-08-24 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_availability_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='rank',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
