# Generated by Django 3.2.6 on 2021-08-25 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shift1employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shift_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift2employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shift_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
