# Generated by Django 3.2.6 on 2021-08-25 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0011_auto_20210825_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='shift1employee',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shift2employee',
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shift'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shiftemployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
