# Generated by Django 3.2.6 on 2021-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
