# Generated by Django 3.2.6 on 2021-08-25 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210826_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='shift',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
