# Generated by Django 3.2.6 on 2021-08-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_availability_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='shiftemployee',
            new_name='employee',
        ),
    ]
