# Generated by Django 3.2.6 on 2021-08-26 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_shiftemployee_schedule_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='rank',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
