# Generated by Django 3.2.6 on 2021-08-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_availability_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
